"""empty message

Revision ID: 6a122625f94c
Revises: e6a59cdeb59b
Create Date: 2025-02-20 18:15:58.249133

"""
from typing import Sequence, Union
from app.models.file import FileType
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a122625f94c'
down_revision: Union[str, None] = 'e6a59cdeb59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file', FileType(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_file_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
